# Generated by Django 3.1.1 on 2020-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0002_remove_answer_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
